In [25]:
import tensorflow as tf

#通过numpy工具包生成模拟数据集
from numpy.random import RandomState

#定义训练数据batch大小
batch_size=8

#定义神经网络参数
w1=tf.Variable(tf.random_normal([2,3],stddev=1,seed=1))
w2=tf.Variable(tf.random_normal([3,1],stddev=1,seed=1))

#在shape的第一个维度使用None，可以方便不同的batch大小
x=tf.placeholder(tf.float32,shape=(None,2),name='x-input')
y_=tf.placeholder(tf.float32,shape=(None,1),name='y-input')

#定义神经网络前向传播过程
a=tf.matmul(x,w1)
y=tf.matmul(a,w2)

#定义损失函数和反向传播算法
cross_entropy=-tf.reduce_mean(y_*tf.log(tf.clip_by_value(y,1e-10,1.0)))
train_step=tf.train.AdamOptimizer(0.001).minimize(cross_entropy)

#通过随机数生成一个模拟数据集
rdm=RandomState(1)
dataset_size=128
X=rdm.rand(dataset_size,2)

#定义规则给出样本标签
Y=[[int(x1+x2<1)] for (x1,x2) in X]

#创建一个会话来运行tensorflow程序
with tf.Session() as sess:
    init_op=tf.initialize_all_variables()
    #初始化变量
    sess.run(init_op)
    print (sess.run(w1))
    print (sess.run(w2))
    
    #设定训练轮数
    STEP=10000
    for i in range(STEP):
        #每次取batch_size个样本进行训练
        start=(i*batch_size)%dataset_size
        end=min(start+batch_size,dataset_size)
        
        #通过选取的样本训练神经网络并更新参数
        feed_dict={x: X[start:end], y_: Y[start:end]}
        sess.run(train_step,feed_dict)
        if i%1000==0:
            #每隔一段时间计算所有数据上的交叉熵并输出
            total_cross_entropy=sess.run(cross_entropy,feed_dict={x:X,y_:Y})
            print('steps:%d,cross entropy on all data:%g'%(i,total_cross_entropy))
    
    print (sess.run(w1))
    print (sess.run(w2))

[[-0.81131822  1.48459876  0.06532937]
 [-2.4427042   0.0992484   0.59122431]]
[[-0.81131822]
 [ 1.48459876]
 [ 0.06532937]]
steps:0,cross entropy on all data:0.0674925
steps:1000,cross entropy on all data:0.0163385
steps:2000,cross entropy on all data:0.00907547
steps:3000,cross entropy on all data:0.00714436
steps:4000,cross entropy on all data:0.00578471
steps:5000,cross entropy on all data:0.00430222
steps:6000,cross entropy on all data:0.00280812
steps:7000,cross entropy on all data:0.00137464
steps:8000,cross entropy on all data:2.11566e-05
steps:9000,cross entropy on all data:-0
[[-2.59392238  3.18602753  2.38825655]
 [-4.1101799   1.68263638  2.83427358]]
[[-2.4300375 ]
 [ 3.33411145]
 [ 2.10067439]]
